### ISSUE TITLE
ArrayIndexOutOfBoundsException when running openaudio

### ISSUE THREAD

**Issue by Andre601** [Mindgamesnl/OpenAudioMc#142]
**Describe the bug**
Running `openaudio` in console causes a ArrayIndexOutOfBoundsException to happen.

Full Stacktrace:
```
[09:53:16 ERROR]: Could not pass event ServerCommandEvent to OpenAudioMc v6.3
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at com.craftmend.openaudiomc.spigot.modules.commands.middleware.CommandTranslationMiddleware.onCommand(CommandTranslationMiddleware.java:32) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor549.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-334]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-334]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-334]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:464) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-334]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**To Reproduce**
1. Run openaudio in console
2. That's it.

**Expected behavior**
The error shouldn't appear

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 (Server)
 - Browser: No Browser used
 - Version: 6.2

**Additional context**

**Comment by Mindgamesnl** [comment]
Oh wow, I might actually be retarded.
Fixed and thanks for letting me know, no clue how this slipped through.
