### ISSUE TITLE
NullPointerException when just running /openaudio speaker <url>

### ISSUE THREAD

**Issue by Andre601** [Mindgamesnl/OpenAudioMc#144]
**Describe the bug**
When just using `/openaudio speaker <url>` without providing a radius does OpenAudioMc respond with a NullPointerException.

**To Reproduce**
1. Use `/openaudio speaker <url>` (Replace URL with a valid url)
2. See error message

**Expected behavior**
The plugin should use default radius and give the speaker.

**Screenshots**
Command:
![2020-07-06_01 46 54](https://user-images.githubusercontent.com/11576465/86544856-bede6900-bf2a-11ea-98fe-35e81598cd8a.png)

Result:
![2020-07-06_01 47 12](https://user-images.githubusercontent.com/11576465/86544859-c271f000-bf2a-11ea-90ef-67ced245afd2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (Server: Ubuntu 18.04)
 - Browser Chrome
 - Version 6.3

**Additional context**

**Comment by Andre601** [comment]
Update: This also happens when you provide a radius

**Comment by Mindgamesnl** [comment]
Could you attach the exception itself? Failed to replicate and can't do anything without it.

**Comment by Andre601** [comment]
There is no exception in the console. Only `java.lang.NullPointerException`

**Comment by Andre601** [comment]
Nevermind. The console for some reason truncated the entire stacktrace...
```
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:?]
	at net.minecraft.server.v1_15_R1.UserCache.a(UserCache.java:126) ~[patched_1.15.2.jar:git-Paper-371]
	at net.minecraft.server.v1_15_R1.UserCache.a(UserCache.java:109) ~[patched_1.15.2.jar:git-Paper-371]
	at net.minecraft.server.v1_15_R1.UserCache.saveProfile(UserCache.java:107) ~[patched_1.15.2.jar:git-Paper-371]
	at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:190) ~[patched_1.15.2.jar:git-Paper-371]
	at net.minecraft.server.v1_15_R1.TileEntitySkull.b(TileEntitySkull.java:214) ~[patched_1.15.2.jar:git-Paper-371]
	at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:95) ~[patched_1.15.2.jar:git-Paper-371]
	at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:518) ~[patched_1.15.2.jar:git-Paper-371]
	at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:42) ~[patched_1.15.2.jar:git-Paper-371]
	at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftInventory.setItem(CraftInventory.java:99) ~[patched_1.15.2.jar:git-Paper-371]
	at com.craftmend.openaudiomc.spigot.services.clicklib.menu.Menu.setItem(Menu.java:33) ~[?:?]
	at com.craftmend.openaudiomc.spigot.modules.speakers.menu.SpeakerMenu.<init>(SpeakerMenu.java:27) ~[?:?]
	at com.craftmend.openaudiomc.spigot.modules.speakers.listeners.SpeakerSelectListener.onClick(SpeakerSelectListener.java:35) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor471.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-371]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-371]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-371]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-371]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:471) ~[patched_1.15.2.jar:git-Paper-371]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:456) ~[patched_1.15.2.jar:git-Paper-371]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1419) ~[patched_1.15.2.jar:git-Paper-371]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-371]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-371]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-371]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-371]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-371]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-371]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-371]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1105) ~[patched_1.15.2.jar:git-Paper-371]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1098) ~[patched_1.15.2.jar:git-Paper-371]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-371]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1059) ~[patched_1.15.2.jar:git-Paper-371]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:974) ~[patched_1.15.2.jar:git-Paper-371]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Mindgamesnl** [comment]
What exact spigot build and/or fork are you using? The item stack seems to be null after lore mutations and name

**Comment by Andre601** [comment]
PaperMC `git-Paper-371 (MC: 1.15.2)`

**Comment by Mindgamesnl** [comment]
We're looking into it on the disocrd

**Comment by Mindgamesnl** [comment]
Fixed by @ApocalypsjeNL, currently pending release https://github.com/ApocalypsjeNL/OpenAudioMc/compare/master...bugfix/speakers
