### ISSUE TITLE
Log Error when using OA

### ISSUE THREAD

**Issue by Rouchesta** [Mindgamesnl/OpenAudioMc#160]
**Describe the bug**
Error in log file. Plugin seems to work fine anyway.

**Desktop (please complete the following information):**
 - Plugin Version: 6.3.7.2
 - Server Version: Paper Tuinity 1.16.4 (build 169)
 - Web client used: default

**Additional context**

`[01:00:02] [Server thread/INFO]: Rouchesta issued server command: /audio
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: java.net.SocketTimeoutException: timeout
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at com.craftmend.thirdparty.okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:677)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at com.craftmend.thirdparty.okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:686)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at com.craftmend.thirdparty.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at com.craftmend.thirdparty.okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at com.craftmend.thirdparty.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at com.craftmend.thirdparty.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at com.craftmend.thirdparty.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at com.craftmend.thirdparty.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at com.craftmend.thirdparty.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at com.craftmend.thirdparty.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at com.craftmend.thirdparty.okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at com.craftmend.thirdparty.okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at com.craftmend.openaudiomc.generic.networking.rest.RestRequest.readHttp(RestRequest.java:91)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at com.craftmend.openaudiomc.generic.networking.rest.RestRequest.executeInThread(RestRequest.java:50)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at com.craftmend.openaudiomc.generic.networking.health.RelayHealthCheck.run(RelayHealthCheck.java:21)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[01:00:11] [Craft Scheduler Thread - 32 - OpenAudioMc/WARN]: [OpenAudioMc] Plugin OpenAudioMc v6.3.7.2 generated an exception while executing task 4551
java.lang.NullPointerException: null
	at com.craftmend.openaudiomc.generic.networking.rest.RestRequest.executeInThread(RestRequest.java:61) ~[?:?]
	at com.craftmend.openaudiomc.generic.networking.health.RelayHealthCheck.run(RelayHealthCheck.java:21) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Tuinity-"957a2ef"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.4.jar:git-Tuinity-"957a2ef"]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Tuinity-"957a2ef"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_272]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_272]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]`

**Comment by Mindgamesnl** [comment]
`SocketTimeoutException`, seems like an issue with your host since it timed out while connecting to our cloudflare worker.

**Comment by Rouchesta** [comment]
Does i need to open a specific port in my forewall maybe ? You use 80 or 443, or both ?

**Comment by Mindgamesnl** [comment]
You shouldn't need to open any ports since they are outgoing connections, it might have been caused by Cloudflare yesterday since multiple parties reported the problem and it seems to have fixed itself.
