### ISSUE TITLE
[OpenAudioMc] Starting authentication module : java.lang.NullPointerException

### ISSUE THREAD

**Issue by geekparadize** [Mindgamesnl/OpenAudioMc#167]
**Describe the bug**
I have an error when launching my server on paper 1.12.2, can you help me to solve this problem.

[18:52:47 INFO]: [OpenAudioMc] Enabling OpenAudioMc v6.3.7.2
[18:52:47 INFO]: [OpenAudioMc] Starting in socket mode
[18:52:47 INFO]: [DiscordSRV] Not using JDBC, one of host/port/database was default
[18:52:47 INFO]: [OpenAudioMc] Starting configuration module
[18:52:47 INFO]: [OpenAudioMc] Starting authentication module
[18:52:48 WARN]: java.lang.NullPointerException
[18:52:48 WARN]: at com.craftmend.openaudiomc.generic.authentication.AuthenticationService.loadData(AuthenticationService.java:66)
[18:52:48 WARN]: at com.craftmend.openaudiomc.generic.authentication.AuthenticationService.initialize(AuthenticationService.java:39)
[18:52:48 WARN]: at com.craftmend.openaudiomc.OpenAudioMc.<init>(OpenAudioMc.java:98)
[18:52:48 WARN]: at com.craftmend.openaudiomc.spigot.OpenAudioMcSpigot.onEnable(OpenAudioMcSpigot.java:81)
[18:52:48 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:52:48 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[18:52:48 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[18:52:48 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[18:52:48 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[18:52:48 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[18:52:48 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[18:52:48 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[18:52:48 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[18:52:48 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[18:52:48 WARN]: at java.lang.Thread.run(Thread.java:748)
[18:52:48 INFO]: [OpenAudioMc] Disabling OpenAudioMc v6.3.7.2
[18:52:48 INFO]: [OpenAudioMc] Shutting down
[18:52:48 ERROR]: Error occurred while disabling OpenAudioMc v6.3.7.2 (Is it up to date?)
java.lang.NullPointerException: null
at com.craftmend.openaudiomc.spigot.OpenAudioMcSpigot.onDisable(OpenAudioMcSpigot.java:119) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:350) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:430) ~[patched_1.12.2.jar:git-Paper-1618]
at com.craftmend.openaudiomc.spigot.OpenAudioMcSpigot.onEnable(OpenAudioMcSpigot.java:109) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**Desktop (please complete the following information):**
 - Plugin Version: 6.3.7.2
 - Server Version: Paper spigot 1.12.2

**Comment by Mindgamesnl** [comment]
Error means that one of the following things went wrong:
 - Your server could not reach our API (host may be blocking it)
 - Your server made too many requests recently (blocked by rate limiting)
 - Your server failed to login too many times (again, rate limiting)

I'd be happy to look into the problem with you in discord to see what exactly is going wrong if you can't find it out on your own, but closing this since it isn't an issue with openaudio but with your setup.
