### ISSUE TITLE
Error Recieving Packet

### ISSUE THREAD

**Issue by mrboog12** [Mindgamesnl/OpenAudioMc#179]
**Describe the bug**
From Console:
```
[23:41:32 INFO]: Error whilst receiving packet com.craftmend.openaudiomc.generic.node.packets.ClientConnectedPacket
[23:41:32 WARN]: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
[23:41:32 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
[23:41:32 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:887)
[23:41:32 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:852)
[23:41:32 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:801)
[23:41:32 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:773)
[23:41:32 WARN]:        at com.craftmend.openaudiomc.generic.node.packets.ClientConnectedPacket.handle(ClientConnectedPacket.java:21)
[23:41:32 WARN]:        at com.craftmend.openaudiomc.api.velocitypluginmessageframework.PacketManager.doPacket(PacketManager.java:174)
[23:41:32 WARN]:        at com.craftmend.openaudiomc.api.velocitypluginmessageframework.PacketManager.dispatchIncomingPacket(PacketManager.java:134)
[23:41:32 WARN]:        at com.craftmend.openaudiomc.api.velocitypluginmessageframework.implementations.BukkitPacketManager.onPluginMessageReceived(BukkitPacketManager.java:52)
[23:41:32 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
[23:41:32 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2911)
[23:41:32 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:44)
[23:41:32 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:9)
[23:41:32 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[23:41:32 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[23:41:32 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[23:41:32 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[23:41:32 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[23:41:32 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1138)
[23:41:32 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1131)
[23:41:32 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[23:41:32 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1092)
[23:41:32 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1006)
[23:41:32 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175)
[23:41:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[23:41:32 WARN]: Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
[23:41:32 WARN]:        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
[23:41:32 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
[23:41:32 WARN]:        ... 24 more
```

**Desktop (please complete the following information):**
 - Plugin Version: 6.5
 - Server Version: Paper 1.16.5 v556
 - Web client used: [default
 - Other setup details: Bungeecord but having audio sent from working URL in command block (issue is only on 1 server on the Bungee, the rest work fine)

**Comment by Mindgamesnl** [comment]
Hey there

the 6.5 update had a small path after release fixing some issues with how internal packets between spigot and proxies are encoded. Please make sure that you're running the exact same jar across your network since this issue seems to indicate that your server is expecting the new format but received the old one from your proxy

**Comment by mrboog12** [comment]
I shutdown all servers and bungee, removed all OA from everything (Saved my regions/alias'/etc offservers) and re-added them after 2 restarts (starting with bungee first so they link correctly) But the one is still not connecting and all are on "6.5" with new generated data/configs
