### ISSUE TITLE
Error with JDK 60

### ISSUE THREAD

**Issue by CloudeLecaw** [Mindgamesnl/OpenAudioMc#183]
This issue appears with java 60 (Java 16) and PaperMC 1.16.5
```
[23:00:38] [Server thread/INFO]: [OpenAudioMc] Enabling OpenAudioMc v6.5.2
[23:00:38] [Server thread/INFO]: [OpenAudioMc] Starting in socket mode
[23:00:38] [Server thread/INFO]: [OpenAudioMc] Starting configuration module
[23:00:38] [Server thread/INFO]: [OpenAudioMc] Starting authentication module
[23:00:38] [Server thread/INFO]: [OpenAudioMc] This server already has an account, skipping sign up.
[23:00:38] [Server thread/INFO]: [OpenAudioMc] Skipped 16 migrations.
[23:00:38] [Server thread/INFO]: [OpenAudioMc] Initializing account details
[23:00:39] [Server thread/INFO]: [OpenAudioMc] Loading aliases...
[23:00:39] [Server thread/INFO]: [OpenAudioMc] Loaded 0 aliases
[23:00:39] [Server thread/INFO]: [OpenAudioMc] Detected version type: MODERN
[23:00:39] [Server thread/INFO]: [OpenAudioMc] Enabling the 1.13 speaker system
[23:00:39] [Server thread/WARN]: java.lang.reflect.InaccessibleObjectException: Unable to make field private final long java.time.Instant.seconds accessible: module java.base does not "opens java.time" to unnamed module @1dd02175
[23:00:39] [Server thread/WARN]: 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[23:00:39] [Server thread/WARN]: 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[23:00:39] [Server thread/WARN]: 	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
[23:00:39] [Server thread/WARN]: 	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
[23:00:39] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:157)
[23:00:39] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
[23:00:39] [Server thread/WARN]: 	at com.google.gson.Gson.getAdapter(Gson.java:423)
[23:00:39] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
[23:00:39] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
[23:00:39] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
[23:00:39] [Server thread/WARN]: 	at com.google.gson.Gson.getAdapter(Gson.java:423)
[23:00:39] [Server thread/WARN]: 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)
[23:00:39] [Server thread/WARN]: 	at com.google.gson.Gson.getAdapter(Gson.java:423)
[23:00:39] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
[23:00:39] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
[23:00:39] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
[23:00:39] [Server thread/WARN]: 	at com.google.gson.Gson.getAdapter(Gson.java:423)
[23:00:39] [Server thread/WARN]: 	at com.google.gson.internal.bind.MapTypeAdapterFactory.create(MapTypeAdapterFactory.java:126)
[23:00:39] [Server thread/WARN]: 	at com.google.gson.Gson.getAdapter(Gson.java:423)
[23:00:39] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
[23:00:39] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
[23:00:39] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
[23:00:39] [Server thread/WARN]: 	at com.google.gson.Gson.getAdapter(Gson.java:423)
[23:00:39] [Server thread/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:886)
[23:00:39] [Server thread/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:852)
[23:00:39] [Server thread/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:801)
[23:00:39] [Server thread/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:773)
[23:00:39] [Server thread/WARN]: 	at com.craftmend.openaudiomc.spigot.modules.predictive.PredictiveMediaModule.loadFromFile(PredictiveMediaModule.java:50)
[23:00:39] [Server thread/WARN]: 	at com.craftmend.openaudiomc.spigot.modules.predictive.PredictiveMediaModule.<init>(PredictiveMediaModule.java:43)
[23:00:39] [Server thread/WARN]: 	at com.craftmend.openaudiomc.spigot.OpenAudioMcSpigot.onEnable(OpenAudioMcSpigot.java:98)
[23:00:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[23:00:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[23:00:39] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[23:00:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[23:00:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[23:00:39] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580)
[23:00:39] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280)
[23:00:39] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055)
[23:00:39] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[23:00:39] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[23:00:39] [Server thread/INFO]: [OpenAudioMc] Disabling OpenAudioMc v6.5.2
[23:00:39] [Server thread/INFO]: [OpenAudioMc] Shutting down
[23:00:39] [Server thread/ERROR]: Error occurred while disabling OpenAudioMc v6.5.2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.craftmend.openaudiomc.spigot.modules.predictive.PredictiveMediaModule.onDisable()" because "this.predictiveMediaService" is null
	at com.craftmend.openaudiomc.spigot.OpenAudioMcSpigot.onDisable(OpenAudioMcSpigot.java:129) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Paper-585]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.5.jar:git-Paper-585]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.5.jar:git-Paper-585]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:508) ~[patched_1.16.5.jar:git-Paper-585]
	at com.craftmend.openaudiomc.spigot.OpenAudioMcSpigot.onEnable(OpenAudioMcSpigot.java:119) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-585]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-585]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-585]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-585]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-585]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580) ~[patched_1.16.5.jar:git-Paper-585]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-585]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-585]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-585]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Mindgamesnl** [comment]
Howdy, could you try deleting your cache.json while your server is off?

**Comment by CloudeLecaw** [comment]
?
This is from the logfile

**Comment by CloudeLecaw** [comment]
WB sorry wfor the late result.
i tried it with a fresh server now. the Reuslt still is the same

```
[11:46:56] [Server thread/INFO]: [OpenAudioMc] Enabling OpenAudioMc v6.5.2
[11:46:56] [Server thread/INFO]: [OpenAudioMc] Starting in socket mode
[11:46:56] [Server thread/INFO]: [OpenAudioMc] Starting configuration module
[11:46:57] [Server thread/INFO]: [OpenAudioMc] Starting authentication module
[11:46:57] [Server thread/INFO]: [OpenAudioMc] This server already has an account, skipping sign up.
[11:46:57] [Server thread/INFO]: [OpenAudioMc] Skipped 16 migrations.
[11:46:57] [Server thread/INFO]: [OpenAudioMc] Initializing account details
[11:46:57] [Server thread/INFO]: [OpenAudioMc] Loading aliases...
[11:46:57] [Server thread/INFO]: [OpenAudioMc] Loaded 0 aliases
[11:46:58] [Server thread/INFO]: [OpenAudioMc] Detected version type: MODERN
[11:46:58] [Server thread/INFO]: [OpenAudioMc] Enabling the 1.13 speaker system
[11:46:58] [Server thread/WARN]: java.lang.reflect.InaccessibleObjectException: Unable to make field private final long java.time.Instant.seconds accessible: module java.base does not "opens java.time" to unnamed module @25a65b77
[11:46:58] [Server thread/WARN]: 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[11:46:58] [Server thread/WARN]: 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[11:46:58] [Server thread/WARN]: 	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
[11:46:58] [Server thread/WARN]: 	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
[11:46:58] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:157)
[11:46:58] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
[11:46:58] [Server thread/WARN]: 	at com.google.gson.Gson.getAdapter(Gson.java:423)
[11:46:58] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
[11:46:58] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
[11:46:58] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
[11:46:58] [Server thread/WARN]: 	at com.google.gson.Gson.getAdapter(Gson.java:423)
[11:46:58] [Server thread/WARN]: 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)
[11:46:58] [Server thread/WARN]: 	at com.google.gson.Gson.getAdapter(Gson.java:423)
[11:46:58] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
[11:46:58] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
[11:46:58] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
[11:46:58] [Server thread/WARN]: 	at com.google.gson.Gson.getAdapter(Gson.java:423)
[11:46:58] [Server thread/WARN]: 	at com.google.gson.internal.bind.MapTypeAdapterFactory.create(MapTypeAdapterFactory.java:126)
[11:46:58] [Server thread/WARN]: 	at com.google.gson.Gson.getAdapter(Gson.java:423)
[11:46:58] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
[11:46:58] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
[11:46:58] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
[11:46:58] [Server thread/WARN]: 	at com.google.gson.Gson.getAdapter(Gson.java:423)
[11:46:58] [Server thread/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:886)
[11:46:58] [Server thread/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:852)
[11:46:58] [Server thread/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:801)
[11:46:58] [Server thread/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:773)
[11:46:58] [Server thread/WARN]: 	at com.craftmend.openaudiomc.spigot.modules.predictive.PredictiveMediaModule.loadFromFile(PredictiveMediaModule.java:50)
[11:46:58] [Server thread/WARN]: 	at com.craftmend.openaudiomc.spigot.modules.predictive.PredictiveMediaModule.<init>(PredictiveMediaModule.java:43)
[11:46:58] [Server thread/WARN]: 	at com.craftmend.openaudiomc.spigot.OpenAudioMcSpigot.onEnable(OpenAudioMcSpigot.java:98)
[11:46:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:46:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[11:46:58] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[11:46:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[11:46:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[11:46:58] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580)
[11:46:58] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280)
[11:46:58] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055)
[11:46:58] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[11:46:58] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[11:46:58] [Server thread/INFO]: [OpenAudioMc] Disabling OpenAudioMc v6.5.2
[11:46:58] [Server thread/INFO]: [OpenAudioMc] Shutting down
[11:46:58] [Server thread/ERROR]: Error occurred while disabling OpenAudioMc v6.5.2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.craftmend.openaudiomc.spigot.modules.predictive.PredictiveMediaModule.onDisable()" because "this.predictiveMediaService" is null
	at com.craftmend.openaudiomc.spigot.OpenAudioMcSpigot.onDisable(OpenAudioMcSpigot.java:129) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Paper-591]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.5.jar:git-Paper-591]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.5.jar:git-Paper-591]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:508) ~[patched_1.16.5.jar:git-Paper-591]
	at com.craftmend.openaudiomc.spigot.OpenAudioMcSpigot.onEnable(OpenAudioMcSpigot.java:119) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-591]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-591]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-591]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-591]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-591]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580) ~[patched_1.16.5.jar:git-Paper-591]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-591]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-591]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-591]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Mindgamesnl** [comment]
The bundled gson build in spigot seems to have issues when trying to serialize Instants, I'll look into shading a newer build or writing a custom type adapter that doesn't do the weird nonsense since we're only really interested in the UNIX timestamp anyway.

**Comment by Mindgamesnl** [comment]
resolved in https://github.com/Mindgamesnl/OpenAudioMc/commit/6a5386a2df15b541397aa1aded4e112bcf8061d6
