### ISSUE TITLE
java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by OverBrave** [Mindgamesnl/OpenAudioMc#275]
**Describe the bug**
```
[12:29:31 INFO]: [OpenAudioMc] Failed to load service: com.craftmend.openaudiomc.generic.database.DatabaseService
[12:29:31 ERROR]: java.lang.reflect.InvocationTargetException
[12:29:31 ERROR]:       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[12:29:31 ERROR]:       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[12:29:31 ERROR]:       at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[12:29:31 ERROR]:       at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[12:29:31 ERROR]:       at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[12:29:31 ERROR]:       at com.craftmend.openaudiomc.generic.service.ServiceManager.loadService(ServiceManager.java:54)
[12:29:31 ERROR]:       at com.craftmend.openaudiomc.generic.service.ServiceManager.loadServices(ServiceManager.java:140)
[12:29:31 ERROR]:       at com.craftmend.openaudiomc.OpenAudioMc.<init>(OpenAudioMc.java:130)
[12:29:31 ERROR]:       at com.craftmend.openaudiomc.velocity.OpenAudioMcVelocity.onProxyInit(OpenAudioMcVelocity.java:71)
[12:29:31 ERROR]:       at com.craftmend.openaudiomc.velocity.Lmbda$19.execute(Unknown Source)
[12:29:31 ERROR]:       at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47)
[12:29:31 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598)
[12:29:31 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479)
[12:29:31 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12:29:31 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12:29:31 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[12:29:31 ERROR]: Caused by: java.lang.NoClassDefFoundError: org/bukkit/plugin/Plugin
[12:29:31 ERROR]:       at java.base/java.lang.Class.forName0(Native Method)
[12:29:31 ERROR]:       at java.base/java.lang.Class.forName(Class.java:467)
[12:29:31 ERROR]:       at com.craftmend.openaudiomc.generic.modules.ModuleLoaderService.loadModFromFile(ModuleLoaderService.java:73)
[12:29:31 ERROR]:       at com.craftmend.openaudiomc.generic.database.DatabaseService.<init>(DatabaseService.java:64)
[12:29:31 ERROR]:       ... 16 more
[12:29:31 ERROR]: Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.Plugin
[12:29:31 ERROR]:       at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:85)
[12:29:31 ERROR]:       at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:62)
[12:29:31 ERROR]:       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[12:29:31 ERROR]:       ... 20 more
```

**Desktop (please complete the following information):**
 - Plugin Version: 6.7
 - Server Version: Velocity 3.1.2-SNAPSHOT (git-74edac96-b153)
 - Web client used: [client.openaudiomc.net (default)]

**Comment by OverBrave** [comment]
[14:54:42 INFO]: [OpenAudioMc] Registering storage table for Alias
[14:54:43 INFO]: [OpenAudioMc] DatabaseService: Registering class <-> table (alias<->Alias.java)
[14:54:43 INFO]: [OpenAudioMc] Registering storage table for ClientDataStore
[14:54:43 INFO]: [OpenAudioMc] DatabaseService: Registering class <-> table (client_data_store<->ClientDataStore.java)
[14:54:43 INFO]: [OpenAudioMc] Registering storage table for MojangProfile
```
[14:54:43 INFO]: [OpenAudioMc] DatabaseService: Registering class <-> table (mojang_profile<->MojangProfile.java)
[14:54:43 INFO]: [OpenAudioMc] Registering storage table for RegionProperties
[14:54:43 INFO]: [OpenAudioMc] DatabaseService: Registering class <-> table (region_properties<->RegionProperties.java)
[14:54:43 INFO]: [OpenAudioMc] Registering storage table for Speaker
[14:54:43 INFO]: [OpenAudioMc] DatabaseService: Registering class <-> table (speaker<->Speaker.java)
[14:54:43 INFO]: [OpenAudioMc] Registering storage table for StoredWorldChunk
[14:54:43 INFO]: [OpenAudioMc] DatabaseService: Registering class <-> table (stored_world_chunk<->StoredWorldChunk.java)
[14:54:43 INFO]: [OpenAudioMc] Registering storage table for MediaRule
[14:54:43 INFO]: [OpenAudioMc] DatabaseService: Registering class <-> table (media_rule<->MediaRule.java)
[14:54:43 INFO]: [OpenAudioMc] Found old legacy database! loading the temporary module to replace it.
[14:54:43 INFO]: [OpenAudioMc] ModuleLoaderService: Loading module migrate.map-to-storm.jar
[14:54:43 INFO]: [OpenAudioMc] ModuleLoaderService: Loading module migrate.map-to-storm.jar as MapDB Migrator
[14:54:43 INFO]: [OpenAudioMc] Initializing account details
[14:54:43 INFO]: [OpenAudioMc] The server is empty! ignoring voice chat.
[14:54:43 INFO]: [OpenAudioMc] [module-MapDB Migrator] Handling SERVICES_LOADED
[14:54:43 INFO]: [OpenAudioMc] [module-MapDB Migrator] Migrating RegionProperties
[14:54:43 INFO]: [OpenAudioMc] Registering storage table for RegionProperties
[14:54:43 INFO]: [OpenAudioMc] [module-MapDB Migrator] Migrating StoredWorldChunk
[14:54:43 INFO]: [OpenAudioMc] Registering storage table for StoredWorldChunk
[14:54:43 INFO]: [OpenAudioMc] [module-MapDB Migrator] Migrating Speaker
[14:54:43 INFO]: [OpenAudioMc] Registering storage table for Speaker
[14:54:43 INFO]: [OpenAudioMc] [module-MapDB Migrator] Migrating Alias
[14:54:43 INFO]: [OpenAudioMc] Registering storage table for Alias
```
Worked! Should I changed on backend server as same jar, or can I still use spigot build?

**Comment by Mindgamesnl** [comment]
You can still use the normal release build :)

Thanks for reporting!
