### ISSUE TITLE
【1.12.2】Cannot load this plugin

### ISSUE THREAD

**Issue by KonohanaSakuya2680** [Mindgamesnl/OpenAudioMc#278]
It used to work fine, but since the update it no longer works.
**Log**
[11:35:06] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: (Player) issued server command: /oa
[11:35:06] [Server thread/ERROR] [net.minecraft.network.NetHandlerPlayServer]: null
org.bukkit.command.CommandException: Cannot execute command 'oa' in plugin OpenAudioMc v6.7 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[PluginCommand.class:git-CatServer-1.12.2-6eb82ffe]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[SimpleCommandMap.class:git-CatServer-1.12.2-6eb82ffe]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:712) ~[CraftServer.class:git-CatServer-1.12.2-6eb82ffe]
	at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:1667) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:1468) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_271]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_271]
	at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:910) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:475) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:834) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]

**Desktop**
 - Plugin Version: 6.7
 - Server Version: CatServer-6eb82ffe (Minecraft 1.12.2)

**Additional context**
English translation using DeepL.

**Comment by Mindgamesnl** [comment]
Please submit the full startup log, this piece isn't of any use.

**Comment by Mindgamesnl** [comment]
Bump, or the issue will be closed today

**Comment by Mindgamesnl** [comment]
Holy shit, I completely forgot about this issue, I'm so sorry!

This could be due to one of two things:

1. The plugin `AutoSaveWorld` seems to log (and possibly block) some required connections during signup
2. Our rest API's were unable to serve your request due to ratelimiting.

I suggest trying to delete the `OpenAudioMc` directory in your plugins folder, and then trying to start wile the `AutoSaveWorld` plugin is disabled.
