### ISSUE TITLE
Time out on Velocity

### ISSUE THREAD

**Issue by OverBrave** [Mindgamesnl/OpenAudioMc#286]
**Describe the bug**
After switch to 6.7.4 from 6.7.3 this errors starting to appear.

```
[01:05:36 INFO]: [OpenAudioMc] Net error: timeout
[01:05:36 ERROR]: java.net.SocketTimeoutException: timeout
[01:05:36 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:677)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:686)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
[01:05:36 ERROR]:       at com.craftmend.openaudiomc.generic.networking.rest.RestRequest.readHttp(RestRequest.java:117)
[01:05:36 ERROR]:       at com.craftmend.openaudiomc.generic.networking.rest.RestRequest.executeInThread(RestRequest.java:69)
[01:05:36 ERROR]:       at com.craftmend.openaudiomc.generic.voicechat.bus.VoiceApiConnection.onWsClose(VoiceApiConnection.java:132)
[01:05:36 ERROR]:       at com.craftmend.openaudiomc.generic.voicechat.bus.VoiceApiConnection.stop(VoiceApiConnection.java:121)
[01:05:36 ERROR]:       at com.craftmend.openaudiomc.generic.networking.drivers.SystemDriver.lambda$boot$1(SystemDriver.java:41)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.emitter.Emitter.emit(Emitter.java:117)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.client.Socket.access$601(Socket.java:24)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.client.Socket$5.run(Socket.java:186)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.thread.EventThread.exec(EventThread.java:55)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.client.Socket.emit(Socket.java:182)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.client.Socket.onclose(Socket.java:275)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.client.Socket.ondisconnect(Socket.java:413)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.client.Socket.onpacket(Socket.java:315)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.client.Socket.access$100(Socket.java:24)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.client.Socket$2$2.call(Socket.java:120)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.emitter.Emitter.emit(Emitter.java:117)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.client.Manager.ondecoded(Manager.java:427)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.client.Manager.access$1600(Manager.java:30)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.client.Manager$7.call(Manager.java:403)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.parser.IOParser$Decoder.add(IOParser.java:105)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.client.Manager.ondata(Manager.java:419)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.client.Manager.access$1000(Manager.java:30)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.client.Manager$2.call(Manager.java:370)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.emitter.Emitter.emit(Emitter.java:117)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.engineio.client.Socket.onPacket(Socket.java:551)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.engineio.client.Socket.access$1000(Socket.java:36)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.engineio.client.Socket$5.call(Socket.java:335)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.emitter.Emitter.emit(Emitter.java:117)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.engineio.client.Transport.onPacket(Transport.java:126)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.engineio.client.Transport.onData(Transport.java:118)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.engineio.client.transports.WebSocket.access$100(WebSocket.java:24)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.engineio.client.transports.WebSocket$1$2.run(WebSocket.java:71)
[01:05:36 ERROR]:       at com.craftmend.thirdparty.iosocket.thread.EventThread$2.run(EventThread.java:80)
[01:05:36 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[01:05:36 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[01:05:36 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[01:05:36 INFO]: [OpenAudioMc] Expected voicechat shut down.
```
```
[00:50:42 INFO]: [OpenAudioMc] Net error: timeout
[00:50:42 ERROR]: java.net.SocketTimeoutException: timeout
[00:50:42 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:677)
[00:50:42 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:686)
[00:50:42 INFO]: [OpenAudioMc] Failed to get relay host.
[00:50:42 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
[00:50:42 INFO]: [OpenAudioMc]  - message: java.net.SocketTimeoutException: timeout
[00:50:42 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
[00:50:42 INFO]: [OpenAudioMc]  - code: BAD_HANDSHAKE
[00:50:42 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
[00:50:42 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
[00:50:42 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[00:50:42 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
[00:50:42 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[00:50:42 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96)
[00:50:42 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[00:50:42 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
[00:50:42 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[00:50:42 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
[00:50:42 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[00:50:42 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
[00:50:42 ERROR]:       at com.craftmend.thirdparty.okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
[00:50:42 ERROR]:       at com.craftmend.openaudiomc.generic.networking.rest.RestRequest.readHttp(RestRequest.java:117)
[00:50:42 ERROR]:       at com.craftmend.openaudiomc.generic.networking.rest.RestRequest.executeInThread(RestRequest.java:69)
[00:50:42 ERROR]:       at com.craftmend.openaudiomc.generic.authentication.driver.AuthenticationDriver.lambda$createPlayerSession$1(AuthenticationDriver.java:69)
[00:50:42 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:228)
[00:50:42 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[00:50:42 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[00:50:42 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[00:50:42 ERROR]: java.io.IOException: Failed to get relay! see console for error information
[00:50:42 ERROR]:       at com.craftmend.openaudiomc.generic.networking.io.SocketIoConnector.setupConnection(SocketIoConnector.java:126)
[00:50:42 ERROR]:       at com.craftmend.openaudiomc.generic.networking.DefaultNetworkingService.lambda$connectIfDown$2(DefaultNetworkingService.java:114)
[00:50:42 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:228)
[00:50:42 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[00:50:42 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[00:50:42 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
```

**Desktop (please complete the following information):**
 - Plugin Version: 6.7.4
 - Server Version: 1.18.2
 - Web client used: [client.openaudiomc.net (default)]
 - Other setup details: Velocity online mode setup

**Comment by Mindgamesnl** [comment]
This seems to be a regular network timeout. Please ping ‘ben.cluster.openaudiomc.net’ to check latency.
