### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by ValhallaCraft** [Mindgamesnl/OpenAudioMc#289]
**Describe the bug**
Console generates the attached exception at random.

**Desktop (please complete the following information):**
 - Plugin Version: 6.7.4
 - Server Version: purpur 1.19.2
 - Web client used: [client.openaudiomc.net (default)]

```diff
  [Tue 15:57:41 INFO  Server/PlayerList] LittleFawkes[/xxxxxx:57740] logged in with entity id 108688 at ([SMP]-4201.247119226377, 63.0, -7707.467322894614)
! [Tue 15:57:41 WARN  OpenAudioMc] Plugin OpenAudioMc v6.7.4 generated an exception while executing task 7768320
java.sql.SQLException: ResultSet closed
	at org.sqlite.core.CoreResultSet.checkOpen(CoreResultSet.java:76)
	at org.sqlite.core.CoreResultSet.markCol(CoreResultSet.java:103)
	at org.sqlite.jdbc3.JDBC3ResultSet.getInt(JDBC3ResultSet.java:395)
	at openaudiomc-6.7.4.jar//com.craftmend.storm.connection.sqlite.SqliteFileDriver.executeUpdate(SqliteFileDriver.java:45)
	at openaudiomc-6.7.4.jar//com.craftmend.storm.Storm.save(Storm.java:316)
	at openaudiomc-6.7.4.jar//com.craftmend.openaudiomc.generic.database.internal.Repository.save(Repository.java:43)
	at openaudiomc-6.7.4.jar//com.craftmend.openaudiomc.generic.client.ClientDataService.lambda$getClientData$0(ClientDataService.java:37)
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Mindgamesnl** [comment]
Alright, I'm on it.
I've also edited your original issue to remove the IP address.

**Comment by ValhallaCraft** [comment]
You'd think I would of noticed I didn't cut out the player join event. Guess that's what no sleep does, thanks for that!

**Comment by Mindgamesnl** [comment]
Sorry for the late response time, school has been incredibly busy.

This issue has now been fixed, and will go live with the update tomorrow or Monday!
