### ISSUE TITLE
java.net.SocketTimeoutException: timeout

### ISSUE THREAD

**Issue by harvanchik** [Mindgamesnl/OpenAudioMc#300]
**Describe the bug**
Warnings when player joins server. SocketTimeoutException

```
[18:10:30 INFO]: UUID of player Flashee is ____________________________________
[18:10:30 INFO]: Flashee [/47.152.50.200:57518] logged in with entity id 63 at ([world]-152.5, 8.0, 65.5)
[18:10:30 INFO]: [OpenAudioMc] [OpenAudioMc] Registering storage table for ClientDataStore
[18:10:31 INFO]: Flashee joined the game (Dec 29, 2022 6:10:31 PM ET)
[18:10:40 INFO]: [OpenAudioMc] [OpenAudioMc] Net error: timeout
[18:10:40 WARN]: java.net.SocketTimeoutException: timeout
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:677)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:686)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.openaudiomc.generic.networking.rest.RestRequest.readHttp(RestRequest.java:117)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.openaudiomc.generic.networking.rest.RestRequest.executeInThread(RestRequest.java:69)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.openaudiomc.generic.authentication.driver.AuthenticationDriver.lambda$createPlayerSession$1(AuthenticationDriver.java:69)
[18:10:40 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[18:10:40 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:10:40 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:10:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:10:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:10:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[18:10:40 INFO]: [OpenAudioMc] [OpenAudioMc] Net error: timeout
[18:10:40 WARN]: java.net.SocketTimeoutException: timeout
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:677)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:686)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.openaudiomc.generic.networking.rest.RestRequest.readHttp(RestRequest.java:117)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.openaudiomc.generic.networking.rest.RestRequest.executeInThread(RestRequest.java:69)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.openaudiomc.generic.networking.io.SocketIoConnector.setupConnection(SocketIoConnector.java:118)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.openaudiomc.generic.networking.DefaultNetworkingService.lambda$connectIfDown$2(DefaultNetworkingService.java:109)
[18:10:40 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[18:10:40 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:10:40 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:10:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:10:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:10:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[18:10:40 INFO]: [OpenAudioMc] [OpenAudioMc] Failed to get relay host.
[18:10:40 INFO]: [OpenAudioMc] [OpenAudioMc]  - message: java.net.SocketTimeoutException: timeout
[18:10:40 INFO]: [OpenAudioMc] [OpenAudioMc]  - code: BAD_HANDSHAKE
[18:10:40 WARN]: java.io.IOException: Failed to get relay! see console for error information
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.openaudiomc.generic.networking.io.SocketIoConnector.setupConnection(SocketIoConnector.java:126)
[18:10:40 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.openaudiomc.generic.networking.DefaultNetworkingService.lambda$connectIfDown$2(DefaultNetworkingService.java:109)
[18:10:40 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[18:10:40 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:10:40 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:10:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:10:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:10:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[18:11:00 INFO]: [OpenAudioMc] [OpenAudioMc] Net error: timeout
[18:11:00 WARN]: java.net.SocketTimeoutException: timeout
[18:11:00 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:677)
[18:11:00 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:686)
[18:11:00 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
[18:11:00 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
[18:11:00 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
[18:11:00 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
[18:11:00 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[18:11:00 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
[18:11:00 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[18:11:00 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96)
[18:11:00 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[18:11:00 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
[18:11:00 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[18:11:00 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
[18:11:00 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
[18:11:00 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
[18:11:00 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.thirdparty.okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
[18:11:00 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.openaudiomc.generic.networking.rest.RestRequest.readHttp(RestRequest.java:117)
[18:11:00 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.openaudiomc.generic.networking.rest.RestRequest.executeInThread(RestRequest.java:69)
[18:11:00 WARN]:        at OpenAudioMc-6.6.2.jar//com.craftmend.openaudiomc.generic.networking.rest.RestRequest.lambda$executeAsync$0(RestRequest.java:62)
[18:11:00 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[18:11:00 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:11:00 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:11:00 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:11:00 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:11:00 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[18:11:00 INFO]: [OpenAudioMc] [OpenAudioMc] Warning, the server returned an error while updating player states!
[18:12:19 INFO]: Flashee lost connection: Disconnected
[18:12:19 INFO]: Flashee left the game (Dec 29, 2022 6:12:19 PM ET)
```

**Desktop (please complete the following information):**
 - Plugin Version: 6.6.2
 - Server Version: Purpur-1632 (MC: 1.18.2)
 - Web client used: [client.openaudiomc.net (default)]

**Comment by Mindgamesnl** [comment]
Please try running the latest version, 6.6.2 is quite old and some api endpoints have since been discontinued.

**Comment by harvanchik** [comment]
Does it still have to be compiled in Java 1.8?

**Comment by Mindgamesnl** [comment]
java 8 should work, though you could also just grab the latest build from spigot.

**Comment by harvanchik** [comment]
Oh, I guess I remembered incorrectly that I have to compile it myself.

**Comment by harvanchik** [comment]
I have upgraded the plugin, but I still am getting these errors. https://paste.sparked.host/yowufiqifa

**Comment by Mindgamesnl** [comment]
Whats your hosting setup like? Seems that its unable to connect to external servers.

Please try `curl https://ben.cluster.openaudiomc.net` over SSH to check if its an issue on your end, as i don't see any firewall block events from the last 24 hours that could be linked to this.

You can find some more details regarding network requirements here; https://help.openaudiomc.net/technical_requirements.html

**Comment by harvanchik** [comment]
I noticed that the [technical requirements](https://help.openaudiomc.net/technical_requirements.html) page reads the following:
> The plugin will use services used on those servers to handle networking, failure to connect to any of them will shut the plugin down since it won’t be able to function properly.
I should mentioned that the OpenAudioMC plugin doesn't disable itself.  As far as I can tell, it still functions.  People are still able to connect to the client and heard the audio that is played.  Those errors are moreso warnings, but they clog up the console which is pretty annoying.  On some occasions, it even freezes the server up for about 10 seconds when someone joins.

**Comment by Mindgamesnl** [comment]
Okay thats properly strange.
I wont be able to respond for a while due to newyears.

Are you able to join our discord? Its a lot easier for quick turnover

**Comment by harvanchik** [comment]
> Okay thats properly strange. I wont be able to respond for a while due to newyears.
> 
> Are you able to join our discord? Its a lot easier for quick turnover

I'm still getting this error which is making my server unplayable.  For now, I have to remove the plugin.  Is there a opportunity to look into this now?  Reopen this issue?
