### ISSUE TITLE
Warn exception in logs SpigotConnection.getClientConnection()" because "p" is null

### ISSUE THREAD

**Issue by AerWyn81** [Mindgamesnl/OpenAudioMc#367]
**Describe the bug**
Hello, I have a log spamming the console and filling the log file (currently 8MB...)
Is this a known problem?

```
[06:41:39] [Craft Scheduler Thread - 204 - OpenAudioMc/WARN]: [OpenAudioMc] Plugin OpenAudioMc v6.8.8 generated an exception while executing task 60
java.lang.NullPointerException: Cannot invoke "com.craftmend.openaudiomc.spigot.modules.players.objects.SpigotConnection.getClientConnection()" because "p" is null
	at com.craftmend.openaudiomc.spigot.modules.voicechat.tasks.PlayerVicinityMessageTask.lambda$run$0(PlayerVicinityMessageTask.java:36) ~[openaudiomc-6.8.8-DEV.jar:?]
	at java.util.ArrayList.removeIf(ArrayList.java:1672) ~[?:?]
	at java.util.ArrayList.removeIf(ArrayList.java:1660) ~[?:?]
	at com.craftmend.openaudiomc.spigot.modules.voicechat.tasks.PlayerVicinityMessageTask.run(PlayerVicinityMessageTask.java:36) ~[openaudiomc-6.8.8-DEV.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.2.jar:git-Purpur-2094]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.2.jar:git-Purpur-2094]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Desktop (please complete the following information):**
 - Plugin Version: v6.8.8
 - Server Version: Purpur 2094 (Mc 1.20.2)
 - Web client used: client.openaudiomc.net
 - Other setup details: Java 17
 
 Let me know if you need more info :)

**Comment by Mindgamesnl** [comment]
A full release including the patch from my previous comment is now available on spigot
