### ISSUE TITLE
Redis setup is broken since 6.8.9

### ISSUE THREAD

**Issue by DiscowZombie** [Mindgamesnl/OpenAudioMc#374]
**Describe the bug**

Turning Redis on (`config.yml` > `redis` > `enabled: true`) throws a `NoSuchMethodError` since 6.8.9. The only change on the config file is the enabling of Redis.

Error printed-out when Redis is on:
```
[11:10:52 INFO]: [OpenAudioMc] Enabling redis service..
[11:10:53 ERROR]: [com.craftmend.thirdparty.reactorcore.publisher.Operators] Operator called default onErrorDropped
java.lang.NoSuchMethodError: 'com.craftmend.thirdparty.ionetty.channel.Channel$Unsafe io.netty.channel.Channel.unsafe()'
	at com.craftmend.thirdparty.ionetty.channel.DefaultChannelPipeline$HeadContext.<init>(DefaultChannelPipeline.java:1312) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.ionetty.channel.DefaultChannelPipeline.<init>(DefaultChannelPipeline.java:98) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.ionetty.channel.AbstractChannel.newChannelPipeline(AbstractChannel.java:120) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.ionetty.channel.AbstractChannel.<init>(AbstractChannel.java:75) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.ionetty.bootstrap.FailedChannel.<init>(FailedChannel.java:33) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.ionetty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:320) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.ionetty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:155) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.ionetty.bootstrap.Bootstrap.connect(Bootstrap.java:139) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.iolettuce.core.AbstractRedisClient.initializeChannelAsync0(AbstractRedisClient.java:409) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.iolettuce.core.AbstractRedisClient.lambda$initializeChannelAsync$2(AbstractRedisClient.java:391) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.reactorcore.publisher.LambdaMonoSubscriber.onNext(LambdaMonoSubscriber.java:168) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.reactorcore.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:203) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.reactorcore.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:173) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.reactorcore.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:845) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.reactorcore.publisher.Operators$MonoSubscriber.complete(Operators.java:1813) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.reactorcore.publisher.MonoCallable.subscribe(MonoCallable.java:62) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.reactorcore.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.reactorcore.publisher.Mono.subscribe(Mono.java:4252) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.reactorcore.publisher.Mono.subscribeWith(Mono.java:4363) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.reactorcore.publisher.Mono.subscribe(Mono.java:4223) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.reactorcore.publisher.Mono.subscribe(Mono.java:4159) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.reactorcore.publisher.Mono.subscribe(Mono.java:4131) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.iolettuce.core.AbstractRedisClient.initializeChannelAsync(AbstractRedisClient.java:386) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.iolettuce.core.RedisClient.connectStatefulAsync(RedisClient.java:325) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.iolettuce.core.RedisClient.connectPubSubAsync(RedisClient.java:419) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.iolettuce.core.RedisClient.connectPubSub(RedisClient.java:336) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.openaudiomc.generic.redis.RedisService.onEnable(RedisService.java:103) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.openaudiomc.generic.service.ServiceManager.loadService(ServiceManager.java:76) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.openaudiomc.generic.service.ServiceManager.loadServices(ServiceManager.java:144) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.openaudiomc.OpenAudioMc.<init>(OpenAudioMc.java:138) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.openaudiomc.spigot.OpenAudioMcSpigot.onEnable(OpenAudioMcSpigot.java:94) ~[openaudiomc-6.8.9(2).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[11:10:53 ERROR]: Error occurred while enabling OpenAudioMc v6.8.9 (Is it up to date?)
java.lang.NoSuchMethodError: 'com.craftmend.thirdparty.ionetty.channel.Channel$Unsafe io.netty.channel.Channel.unsafe()'
	at com.craftmend.thirdparty.ionetty.channel.DefaultChannelPipeline$HeadContext.<init>(DefaultChannelPipeline.java:1312) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.ionetty.channel.DefaultChannelPipeline.<init>(DefaultChannelPipeline.java:98) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.ionetty.channel.AbstractChannel.newChannelPipeline(AbstractChannel.java:120) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.ionetty.channel.AbstractChannel.<init>(AbstractChannel.java:75) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.ionetty.bootstrap.FailedChannel.<init>(FailedChannel.java:33) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.ionetty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:320) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.ionetty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:155) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.ionetty.bootstrap.Bootstrap.connect(Bootstrap.java:139) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.iolettuce.core.AbstractRedisClient.initializeChannelAsync0(AbstractRedisClient.java:409) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.iolettuce.core.AbstractRedisClient.lambda$initializeChannelAsync$2(AbstractRedisClient.java:391) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.reactorcore.publisher.LambdaMonoSubscriber.onNext(LambdaMonoSubscriber.java:168) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.reactorcore.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:203) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.reactorcore.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:173) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.reactorcore.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:845) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.reactorcore.publisher.Operators$MonoSubscriber.complete(Operators.java:1813) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.reactorcore.publisher.MonoCallable.subscribe(MonoCallable.java:62) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.reactorcore.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.reactorcore.publisher.Mono.subscribe(Mono.java:4252) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.reactorcore.publisher.Mono.subscribeWith(Mono.java:4363) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.reactorcore.publisher.Mono.subscribe(Mono.java:4223) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.reactorcore.publisher.Mono.subscribe(Mono.java:4159) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.reactorcore.publisher.Mono.subscribe(Mono.java:4131) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.iolettuce.core.AbstractRedisClient.initializeChannelAsync(AbstractRedisClient.java:386) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.iolettuce.core.RedisClient.connectStatefulAsync(RedisClient.java:325) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.iolettuce.core.RedisClient.connectPubSubAsync(RedisClient.java:419) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.thirdparty.iolettuce.core.RedisClient.connectPubSub(RedisClient.java:336) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.openaudiomc.generic.redis.RedisService.onEnable(RedisService.java:103) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.openaudiomc.generic.service.ServiceManager.loadService(ServiceManager.java:76) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.openaudiomc.generic.service.ServiceManager.loadServices(ServiceManager.java:144) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.openaudiomc.OpenAudioMc.<init>(OpenAudioMc.java:138) ~[openaudiomc-6.8.9(2).jar:?]
	at com.craftmend.openaudiomc.spigot.OpenAudioMcSpigot.onEnable(OpenAudioMcSpigot.java:94) ~[openaudiomc-6.8.9(2).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[11:10:53 INFO]: [OpenAudioMc] Disabling OpenAudioMc v6.8.9
[11:10:53 INFO]: [OpenAudioMc] Shutting down
[11:10:53 INFO]: [OpenAudioMc] Field openAudioMcSpigot in SpigotPlayerService is null, this is probably a bug

```

**Desktop (please complete the following information):**
 - Plugin Version: 6.8.9 (since the GH release is missing, [I downloaded from Spigot](https://www.spigotmc.org/resources/openaudiomc-proximity-voice-chat-and-music-without-mods.30691/history))
 - Server Version: Tested with Paper 1.20.1 (Java 17) and Spigot 1.8.8 (Java 8) - no one works. The exact same setup work with OAMC 6.8.8.

**Comment by DiscowZombie** [comment]
Never mind, the issue seems fixed since https://github.com/Mindgamesnl/OpenAudioMc/commit/1f2a8b877a06538970e614c373255b915c3dfe95.
