### ISSUE TITLE
WARN]: [OpenAudioMc] WARNING: Failed to load service: com.craftmend.openaudiomc.generic.modules.ModuleLoaderService - null

### ISSUE THREAD

**Issue by qeqbwd** [Mindgamesnl/OpenAudioMc#416]
[23:56:13 INFO]: [OpenAudioMc] Enabling OpenAudioMc v6.10.0
[23:56:13 INFO]: [OpenAudioMc] [info] Starting OpenAudioMc, build 1401 by Mats
[23:56:13 INFO]: [OpenAudioMc] [info] Using the main config file..
[23:56:13 INFO]: [OpenAudioMc] [info] Starting configuration module
[23:56:13 INFO]: [OpenAudioMc] [info] Using the main config file..
[23:56:13 INFO]: [OpenAudioMc] [info] Starting configuration module
[23:56:13 INFO]: [OpenAudioMc] [info] Detected md_5 chat support, using default user adapter
[23:56:13 INFO]: [OpenAudioMc] [info] Skipped 42/42 migrations.
[23:56:13 INFO]: [OpenAudioMc] [info] ModuleLoaderService: Downloading default migration module
[23:56:14 WARN]: [OpenAudioMc] WARNING: Failed to load service: com.craftmend.openaudiomc.generic.modules.ModuleLoaderService - null
[23:56:14 ERROR]: [OpenAudioMc] OpenAudioMc-Err: A fatal error occurred while enabling OpenAudioMc. The plugin will now disable itself.
java.lang.reflect.InvocationTargetException
[23:56:14 WARN]: java.lang.reflect.InvocationTargetException
[23:56:14 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:7
9)
[23:56:14 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[23:56:14 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
[23:56:14 WARN]:        at openaudiomc-6.10.0.jar//com.craftmend.openaudiomc.generic.service.ServiceManager.loadService(ServiceManager.java:
53)
[23:56:14 WARN]:        at openaudiomc-6.10.0.jar//com.craftmend.openaudiomc.OpenAudioMc.<init>(OpenAudioMc.java:135)
[23:56:14 WARN]:        at openaudiomc-6.10.0.jar//com.craftmend.openaudiomc.spigot.OpenAudioMcSpigot.onEnable(OpenAudioMcSpigot.java:95)
[23:56:14 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[23:56:14 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[23:56:14 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[23:56:14 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[23:56:14 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
[23:56:14 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
[23:56:14 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
[23:56:14 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
[23:56:14 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[23:56:14 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
[23:56:14 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[23:56:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[23:56:14 WARN]: Caused by: java.net.UnknownHostException: raw.githubusercontent.com
[23:56:14 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:560)
[23:56:14 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[23:56:14 WARN]:        at java.base/java.net.Socket.connect(Socket.java:666)
[23:56:14 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[23:56:14 WARN]:        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:181)
[23:56:14 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[23:56:14 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
[23:56:14 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
[23:56:14 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[23:56:14 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:378)
[23:56:14 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURL
Connection.java:193)
[23:56:14 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1241)
[23:56:14 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1127)
[23:56:14 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnectio
n.java:179)
[23:56:14 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2898)
[23:56:14 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2807)
[23:56:14 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getI

 - Plugin Version: 6.10.0
 - Server Version:  Paper spigot 1.20.1
 - Web client used: [client.openaudiomc.net (default)]

**Comment by Mindgamesnl** [comment]
Your server us unable to make an outgoing request to the public internet, in this case failing to resolve a domain from github. This is an issue on your end.
