### ISSUE TITLE
error

### ISSUE THREAD

**Issue by poma123** [Mindgamesnl/OpenAudioMc#70]
A long error... 
```
05.01 19:15:34 [Server] ERROR Could not pass event SocketWhisperEvent to OpenAudioMc v2.6
05.01 19:15:34 [Server] INFO org.bukkit.event.EventException: null
05.01 19:15:34 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1293]
05.01 19:15:34 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1293]
05.01 19:15:34 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1293]
05.01 19:15:34 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1293]
05.01 19:15:34 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [patched_1.12.2.jar:git-Paper-1293]
05.01 19:15:34 [Server] INFO at net.openaudiomc.socket.SocketioConnector.whisper(SocketioConnector.java:126) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at net.openaudiomc.socket.SocketioConnector$3.call(SocketioConnector.java:83) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.emitter.Emitter.emit(Emitter.java:117) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.client.Socket.onevent(Socket.java:340) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.client.Socket.onpacket(Socket.java:293) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.client.Socket.access$100(Socket.java:19) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.client.Socket$2$2.call(Socket.java:111) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.emitter.Emitter.emit(Emitter.java:117) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.client.Manager.ondecoded(Manager.java:407) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.client.Manager.access$1600(Manager.java:20) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.client.Manager$7.call(Manager.java:383) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.emitter.Emitter.emit(Emitter.java:117) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.parser.Parser$Decoder.add(Parser.java:157) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.client.Manager.ondata(Manager.java:399) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.client.Manager.access$1000(Manager.java:20) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.client.Manager$2.call(Manager.java:350) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.emitter.Emitter.emit(Emitter.java:117) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.engineio.client.Socket.onPacket(Socket.java:511) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.engineio.client.Socket.access$1000(Socket.java:31) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.engineio.client.Socket$5.call(Socket.java:313) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.emitter.Emitter.emit(Emitter.java:117) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.engineio.client.Transport.onPacket(Transport.java:134) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.engineio.client.Transport.onData(Transport.java:126) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:24) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.engineio.client.transports.WebSocket$2$2.run(WebSocket.java:99) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.thread.EventThread$2.run(EventThread.java:80) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
05.01 19:15:34 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
05.01 19:15:34 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
05.01 19:15:34 [Server] INFO Caused by: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
05.01 19:15:34 [Server] INFO at org.json.JSONTokener.syntaxError(JSONTokener.java:451) ~[?:?]
05.01 19:15:34 [Server] INFO at org.json.JSONObject.<init>(JSONObject.java:196) ~[?:?]
05.01 19:15:34 [Server] INFO at org.json.JSONObject.<init>(JSONObject.java:320) ~[?:?]
05.01 19:15:34 [Server] INFO at net.openaudiomc.core.EventListener.onSocketWhisperEvent(EventListener.java:72) ~[?:?]
05.01 19:15:34 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor317.execute(Unknown Source) ~[?:?]
05.01 19:15:34 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1293]
05.01 19:15:34 [Server] INFO ... 33 more
05.01 19:15:34 [Server] ERROR Could not pass event SocketWhisperEvent to OpenAudioMc v2.6
05.01 19:15:34 [Server] INFO org.bukkit.event.EventException: null
05.01 19:15:34 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1293]
05.01 19:15:34 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1293]
05.01 19:15:34 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1293]
05.01 19:15:34 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1293]
05.01 19:15:34 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [patched_1.12.2.jar:git-Paper-1293]
05.01 19:15:34 [Server] INFO at net.openaudiomc.socket.SocketioConnector.whisper(SocketioConnector.java:126) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at net.openaudiomc.socket.SocketioConnector$3.call(SocketioConnector.java:83) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.emitter.Emitter.emit(Emitter.java:117) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.client.Socket.onevent(Socket.java:340) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.client.Socket.onpacket(Socket.java:293) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.client.Socket.access$100(Socket.java:19) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.client.Socket$2$2.call(Socket.java:111) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.emitter.Emitter.emit(Emitter.java:117) [OpenAudioMc-2.6.jar:?]
05.01 19:15:34 [Server] INFO at io.socket.client.Manager.ondecoded(Manager.java:407) [OpenAudioMc-2.6.jar:?]
```

**Comment by ApocalypsjeNL** [comment]
We already know this error and we're working on a new release (full recode) which fixes a whole lot of bugs and errors. Stay tuned and thanks for reporting!

**Comment by poma123** [comment]
Okay, and Thanks in advance! 👍
