### ISSUE TITLE
NPE on Server-Stop

### ISSUE THREAD

**Issue by Sprax2013** [Mindgamesnl/OpenAudioMc#72]
When I type 'stop' (I never use 'reload') into the console, I'm getting this NullPointerException:
```
[19:02:12] [Server thread/ERROR]: Error occurred while disabling OpenAudioMc v2.6 (Is it up to date?)
java.lang.NullPointerException: null
	at net.openaudiomc.socket.SocketioConnector.close(SocketioConnector.java:106) ~[?:?]
	at net.openaudiomc.core.Main.onDisable(Main.java:112) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-f4ca180]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot-1.12.2.jar:git-Spigot-4bd94dc-f4ca180]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:422) [spigot-1.12.2.jar:git-Spigot-4bd94dc-f4ca180]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:415) [spigot-1.12.2.jar:git-Spigot-4bd94dc-f4ca180]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:349) [spigot-1.12.2.jar:git-Spigot-4bd94dc-f4ca180]
	at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:465) [spigot-1.12.2.jar:git-Spigot-4bd94dc-f4ca180]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:613) [spigot-1.12.2.jar:git-Spigot-4bd94dc-f4ca180]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by ApocalypsjeNL** [comment]
Did anybody connect to the webclient with /audio while the server was up?

**Comment by Sprax2013** [comment]
Nobody. I started the Server. Tested my Plugin and restarted with an updated version of my plugin. I was the only one who joined and did not connect to the WebClient

**Comment by ApocalypsjeNL** [comment]
Well I know the problem already then, hopefully a fix can get pushed soon

**Comment by ApocalypsjeNL** [comment]
Update is coming today or tomorrow, stay tuned!

**Comment by ApocalypsjeNL** [comment]
Update is live, gonna close the issue then. If you've any bugs feel free to reopen it. https://www.spigotmc.org/resources/openaudiomc-open-source-audio-client.30691/update?update=212895
