### ISSUE TITLE
Regions don't work with WebServer

### ISSUE THREAD

**Issue by Engineer204** [Mindgamesnl/OpenAudioMc#79]
OpenAudioMc Version: 4.0

Spigot Version: spigot-1.12.2-R0.1-SNAPSHOT-b1605

WorldGuard Version: 6.2.1

Description of the problem: Not sure if at this moment its not working or it hasn't been working at all, but I can't get world edit regions to play area music

How to replicate the issue: Start a web server with the GitHub given web client, and try to get the regions to work :)

**Comment by Mindgamesnl** [comment]
The github version of the webclient is the same version as on our web server, do you have any console error's?

**Comment by Engineer204** [comment]
I am not receiving any console errors that I can see.

**Comment by FantasyNetworkMC** [comment]
I am having the same issue. No region audio on the page

**Comment by FantasyNetworkMC** [comment]
Oh also I have an error message :) Initializing region: spawn
[14:42:20 WARN]: [OpenAudioMc] Plugin OpenAudioMc v4.0 generated an exception while executing task 1011
java.lang.IllegalArgumentException: null
	at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:278) ~[?:1.8.0_161]
	at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:50) ~[?:1.8.0_161]
	at com.mpatric.mp3agic.Mp3File.initId3v1Tag(Mp3File.java:273) ~[?:?]
	at com.mpatric.mp3agic.Mp3File.init(Mp3File.java:94) ~[?:?]
	at com.mpatric.mp3agic.Mp3File.<init>(Mp3File.java:58) ~[?:?]
	at com.mpatric.mp3agic.Mp3File.<init>(Mp3File.java:45) ~[?:?]
	at net.openaudiomc.jclient.utils.Mp3Reader.lambda$run$0(Mp3Reader.java:33) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-4bd94dc-fd702e4]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-4bd94dc-fd702e4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by ApocalypsjeNL** [comment]
That's something else, that indicates that the temp file is null

**Comment by Engineer204** [comment]
Okay after a ton of testing I found that for some reason only region audio doesn't work with Kiwi 6 on version 4 for some reason. Is there another mp3 hosting website that you would reccomend?

**Comment by ApocalypsjeNL** [comment]
https://audioload.nl

**Comment by Engineer204** [comment]
Alright thank you! If you could add kiwi6 support for regions again, that would be nice. If not it's fine. Thanks for all you do :)
