### ISSUE TITLE
Openaudio crash after server start

### ISSUE THREAD

**Issue by Rouchesta** [Mindgamesnl/OpenAudioMc#82]
Openaudio 4.0
Spigot 1.12.2

Openaudio seems to be loaded and then crash after these errors.

```
[06:01:52] [Server thread/INFO]: [OpenAudioMc] Enabling OpenAudioMc v4.0
[06:01:52] [Server thread/WARN]: [AutoSaveWorld] Plugin OpenAudioMc attempted to establish connection https://cdn.snowdns.de/oa.json in main server thread
[06:01:52] [Server thread/WARN]: [AutoSaveWorld] Plugin OpenAudioMc attempted to establish connection socket://cdn.snowdns.de:443 in main server thread
[06:01:52] [Server thread/INFO]: [OpenAudioMc] This is your first time using OpenAudioMc! welcome! (getting client cridentials)
[06:01:52] [Server thread/WARN]: [AutoSaveWorld] Plugin OpenAudioMc attempted to establish connection https://cdn.snowdns.de/oa.json in main server thread
[06:01:52] [Server thread/WARN]: [AutoSaveWorld] Plugin OpenAudioMc attempted to establish connection https://craftmendserver.eu:6969/genid in main server thread
[06:01:52] [Server thread/WARN]: [AutoSaveWorld] Plugin OpenAudioMc attempted to establish connection socket://craftmendserver.eu:6969 in main server thread
[06:03:59] [Server thread/WARN]: java.net.ConnectException: Connection timed out
[06:03:59] [Server thread/WARN]: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[06:03:59] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[06:03:59] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[06:03:59] [Server thread/WARN]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[06:03:59] [Server thread/WARN]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[06:03:59] [Server thread/WARN]: 	at java.net.Socket.connect(Socket.java:589)
[06:03:59] [Server thread/WARN]: 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
[06:03:59] [Server thread/WARN]: 	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[06:03:59] [Server thread/WARN]: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[06:03:59] [Server thread/WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
[06:03:59] [Server thread/WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
[06:03:59] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[06:03:59] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[06:03:59] [Server thread/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[06:03:59] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
[06:03:59] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
[06:03:59] [Server thread/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[06:03:59] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
[06:03:59] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
[06:03:59] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[06:03:59] [Server thread/WARN]: 	at net.openaudiomc.jclient.utils.UrlFetcher.run(UrlFetcher.java:21)
[06:03:59] [Server thread/WARN]: 	at net.openaudiomc.jclient.modules.socket.objects.KeyHolder.<init>(KeyHolder.java:26)
[06:03:59] [Server thread/WARN]: 	at net.openaudiomc.jclient.modules.socket.SocketModule.<init>(SocketModule.java:33)
[06:03:59] [Server thread/WARN]: 	at net.openaudiomc.jclient.OpenAudioMc.onEnable(OpenAudioMc.java:41)
[06:03:59] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[06:03:59] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[06:03:59] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[06:03:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382)
[06:03:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331)
[06:03:59] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[06:03:59] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[06:03:59] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[06:03:59] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[06:03:59] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[06:03:59] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[06:03:59] [Server thread/ERROR]: Error occurred while enabling OpenAudioMc v4.0 (Is it up to date?)
java.lang.NullPointerException: null
	at java.io.StringReader.<init>(StringReader.java:50) ~[?:1.8.0_91]
	at org.json.JSONTokener.<init>(JSONTokener.java:85) ~[?:?]
	at org.json.JSONObject.<init>(JSONObject.java:319) ~[?:?]
	at net.openaudiomc.jclient.modules.socket.objects.KeyHolder.<init>(KeyHolder.java:28) ~[?:?]
	at net.openaudiomc.jclient.modules.socket.SocketModule.<init>(SocketModule.java:33) ~[?:?]
	at net.openaudiomc.jclient.OpenAudioMc.onEnable(OpenAudioMc.java:41) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

```
[18:41:43] [Server thread/ERROR]: Could not pass event BlockBreakEvent to OpenAudioMc v4.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:290) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:217) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:889) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
	at net.openaudiomc.jclient.modules.player.listeners.SpeakerPlaceBreakListener.onDestroy(SpeakerPlaceBreakListener.java:43) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor494.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	... 17 more

**How to replicate the issue:** 
<!--- If you can reproduce the issue please tell us as detailed as possible step by step how to do that -->
```

**Comment by Legoman99573** [comment]
issue is your server cant reach the socket server if it timed out. Maybe the host trottles the connection to the socket server.

**Comment by Rouchesta** [comment]
Is there any change about this socket since v2 ? I remember i had problem like this a long time ago and one of you solved it by changing socket or ... can't remember.

**Comment by SnowBlinderP** [comment]
@Rouchesta | At the Moment theres no Alternative Socket from ur Side

**Comment by Rouchesta** [comment]
I resolved the issue when the plugin start. It don't generate private and public key.
I had to go on a link which has generated for me the private and public key.
I copied these manually to the config file and restarted the plugin.
I can now use commands.

**Comment by Rouchesta** [comment]
We really need a step by step installation tutorial ...
