### ISSUE TITLE
NullPounterException on BlockBreakEvent

### ISSUE THREAD

**Issue by Sprax2013** [Mindgamesnl/OpenAudioMc#85]
# Issue Template

**OpenAudioMc Version:** 4.0

**Spigot Version:** CraftBukkit version git-Spigot-c3093ef-7e94e65 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**WorldGuard Version:** 6.2.1;84bc322

**Description of the problem:** 

```
[12:57:35] [Server thread/ERROR]: Could not pass event BlockBreakEvent to OpenAudioMc v4.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:290) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:217) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:889) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at net.openaudiomc.jclient.modules.player.listeners.SpeakerPlaceBreakListener.onDestroy(SpeakerPlaceBreakListener.java:43) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	... 17 more
```
**How to replicate the issue:** 

I could not replicate the issue. I luckily saw the StackTrace in the console.

**Comment by SnowBlinderP** [comment]
What happened @ that Moment (Placed Block?)
 Issue Template
OpenAudioMc Version: 4.0
Spigot Version: CraftBukkit version git-Spigot-c3093ef-7e94e65 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
WorldGuard Version: 6.2.1;84bc322
Description of the problem:[12:57:35] [Server thread/ERROR]: Could not pass event BlockBreakEvent to OpenAudioMc v4.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:290) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:217) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:889) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at net.openaudiomc.jclient.modules.player.listeners.SpeakerPlaceBreakListener.onDestroy(SpeakerPlaceBreakListener.java:43) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-7e94e65]
	... 17 more

How to replicate the issue:
I could not replicate the issue. I luckily saw the StackTrace in the console.

**Comment by Sprax2013** [comment]
According to the error:
`Could not pass event BlockBreakEvent to OpenAudioMc v4.0`
`Caused by: java.lang.NullPointerException`
`net.openaudiomc.jclient.modules.player.listeners.SpeakerPlaceBreakListener.onDestroy(SpeakerPlaceBreakListener.java:43)`

I'm not sure what you want to know

**Comment by SnowBlinderP** [comment]
What did u do @ that Exact Moment?

**Comment by Sprax2013** [comment]
I didn't do anything. I wasn't even online. I needed to restart the server and saw this on the console (3 players were online).
Maybe I should add that the plugin is not in use currently. It is installed and you could connect to the Audio-Client but there are no sounds that would be played automatically.

**Comment by SnowBlinderP** [comment]
Weird ;/ | I will look into that later when im @ home :D

**Comment by ApocalypsjeNL** [comment]
Line 43 is a piece of code which checks the skullOwner's username, somehow that's null.

**Comment by Mindgamesnl** [comment]
Fixed for new release in 2019 rewrite.
