### ISSUE TITLE
Speaker not working

### ISSUE THREAD

**Issue by wesley9946** [Mindgamesnl/OpenAudioMc#86]
Hi there,

I'm trying to get internet radio stations working on speakers, but there is no sound.
When I reload/restart the server, i get the following Java exception in the console:

[05:04:43]  [Craft Scheduler Thread - 8/WARN]: [OpenAudioMc] Plugin OpenAudioMc  v4.0 generated an exception while executing task 92
--
java.lang.IllegalArgumentException: null
at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:278) ~[?:1.8.0_151]
at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:50) ~[?:1.8.0_151]
at com.mpatric.mp3agic.Mp3File.initId3v1Tag(Mp3File.java:273) ~[?:?]
at com.mpatric.mp3agic.Mp3File.init(Mp3File.java:94) ~[?:?]
at com.mpatric.mp3agic.Mp3File.<init>(Mp3File.java:58) ~[?:?]
at com.mpatric.mp3agic.Mp3File.<init>(Mp3File.java:45) ~[?:?]
at net.openaudiomc.jclient.utils.Mp3Reader.lambda$run$0(Mp3Reader.java:33) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-7862817-bd30843]
at  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)  [spigot-1.12.2.jar:git-Spigot-7862817-bd30843]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

Can you fix it or tell me what's wrong?

**Comment by SnowBlinderP** [comment]
Internet Radio Station Streams are not Officially supported at the Moment

**Comment by Mindgamesnl** [comment]
Fixed for new relese in 2019 rewrite.
