### ISSUE TITLE
Spamming Logs MultiWorld

### ISSUE THREAD

**Issue by Rouchesta** [Mindgamesnl/OpenAudioMc#90]
Hi all,

**OpenAudioMc Version:** 
4.0
**Spigot Version:**
1.12.2
**WorldGuard Version:**
6.2.2

**Description of the problem:** 
The log file is spammed when a player is in another world and type /audio.
It's something about speaker loaded but not in the same world for the source player.

[19:22:52] [Server thread/WARN]: [OpenAudioMc] Task #339 for OpenAudioMc v4.0 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between Donjon and Licorne
	at org.bukkit.Location.distanceSquared(Location.java:460) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at org.bukkit.Location.distance(Location.java:443) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at net.openaudiomc.jclient.modules.player.objects.AudioListener.lambda$updateSpeakers$1(AudioListener.java:60) ~[?:?]
	at java.util.ArrayList.removeIf(ArrayList.java:1405) ~[?:1.8.0_91]
	at net.openaudiomc.jclient.modules.player.objects.AudioListener.updateSpeakers(AudioListener.java:60) ~[?:?]
	at net.openaudiomc.jclient.modules.media.tasks.PlayerSpeakerCheck.run(PlayerSpeakerCheck.java:11) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2-R0.1-SNAPSHOT-b1480.jar:git-Spigot-549c1fa-8c37e2e]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

**How to replicate the issue:** 
Typing /audio command.

Thank you for the help provided ;-)

**Comment by Mindgamesnl** [comment]
Fixed for new relese in 2019 rewrite.
