### ISSUE TITLE
Cant create Speakers/Regions - Error "now in the old default mode"

### ISSUE THREAD

**Issue by MrZybez** [Mindgamesnl/OpenAudioMc#91]
I'm trying to make a speaker.  Current server is 1.8.9 Spigot. The other /oa play <name> <URL> works just fine.  Only region creation and speaker creation doesn't work. It give off this similar error for both.

[14:48:12] [Server thread/INFO]: ZevexZybez issued server command: /oa speaker create https://www.youtube.com/watch?v=t2rs-OyJ-Q8
[14:48:39] [Server thread/INFO]: [OpenAudioMc] Initializing speaker: https://www--_--youtube--_--com/watch?v=t2rs-OyJ-Q8
[14:48:39] [Server thread/INFO]: [OpenAudioMc] Initializing speaker: https://www--_--youtube--_--com/watch?v=t2rs-OyJ-Q8
[14:48:39] [Craft Scheduler Thread - 231/INFO]: [OpenAudioMc] Failed to create syncronized speaker, speaker is now in the old default mode: https://www--_--youtube--_--com/watch?v=t2rs-OyJ-Q8
[14:48:39] [Craft Scheduler Thread - 231/WARN]: com.mpatric.mp3agic.InvalidDataException: No mpegs frames found
[14:48:39] [Craft Scheduler Thread - 231/WARN]: 	at com.mpatric.mp3agic.Mp3File.init(Mp3File.java:97)
[14:48:39] [Craft Scheduler Thread - 231/WARN]: 	at com.mpatric.mp3agic.Mp3File.<init>(Mp3File.java:58)
[14:48:39] [Craft Scheduler Thread - 231/WARN]: 	at com.mpatric.mp3agic.Mp3File.<init>(Mp3File.java:45)
[14:48:39] [Craft Scheduler Thread - 231/WARN]: 	at net.openaudiomc.jclient.utils.Mp3Reader.lambda$run$0(Mp3Reader.java:33)
[14:48:39] [Craft Scheduler Thread - 231/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[14:48:39] [Craft Scheduler Thread - 231/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[14:48:39] [Craft Scheduler Thread - 231/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:48:39] [Craft Scheduler Thread - 231/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:48:39] [Craft Scheduler Thread - 231/WARN]: 	at java.lang.Thread.run(Unknown Source)
[14:48:39] [Craft Scheduler Thread - 229/INFO]: [OpenAudioMc] Failed to create syncronized speaker, speaker is now in the old default mode: https://www--_--youtube--_--com/watch?v=t2rs-OyJ-Q8
[14:48:39] [Craft Scheduler Thread - 229/WARN]: com.mpatric.mp3agic.InvalidDataException: No mpegs frames found
[14:48:39] [Craft Scheduler Thread - 229/WARN]: 	at com.mpatric.mp3agic.Mp3File.init(Mp3File.java:97)
[14:48:39] [Craft Scheduler Thread - 229/WARN]: 	at com.mpatric.mp3agic.Mp3File.<init>(Mp3File.java:58)
[14:48:39] [Craft Scheduler Thread - 229/WARN]: 	at com.mpatric.mp3agic.Mp3File.<init>(Mp3File.java:45)
[14:48:39] [Craft Scheduler Thread - 229/WARN]: 	at net.openaudiomc.jclient.utils.Mp3Reader.lambda$run$0(Mp3Reader.java:33)
[14:48:39] [Craft Scheduler Thread - 229/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[14:48:39] [Craft Scheduler Thread - 229/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[14:48:39] [Craft Scheduler Thread - 229/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:48:39] [Craft Scheduler Thread - 229/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:48:39] [Craft Scheduler Thread - 229/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by Mindgamesnl** [comment]
Fixed for new relese in 2019 rewrite.
