### ISSUE TITLE
UnsupportedOperationException (Java 10)

### ISSUE THREAD

**Issue by poma123** [Mindgamesnl/OpenAudioMc#92]
**OpenAudioMc Version: 4.0** 

**Spigot Version: Paper version git-Paper-1436 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)**

**WorldGuard Version: 6.2.2-SNAPSHOT;1710-95b88ea**

**Description of the problem: The plugin seems to be incompatible with Java 10.**
```
11.06 08:16:41 [Server] ERROR [io.socket.thread.EventThread] Task threw exception
11.06 08:16:41 [Server] INFO java.lang.UnsupportedOperationException: clientBuilder.sslSocketFactory(SSLSocketFactory) not supported on JDK 9+
11.06 08:16:41 [Server] INFO at okhttp3.internal.platform.Jdk9Platform.trustManager(Jdk9Platform.java:78) ~[OpenAudioMc.jar:?]
11.06 08:16:41 [Server] INFO at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.java:651) ~[OpenAudioMc.jar:?]
11.06 08:16:41 [Server] INFO at io.socket.engineio.client.transports.WebSocket.doOpen(WebSocket.java:50) ~[OpenAudioMc.jar:?]
11.06 08:16:41 [Server] INFO at io.socket.engineio.client.Transport$1.run(Transport.java:82) ~[OpenAudioMc.jar:?]
11.06 08:16:41 [Server] INFO at io.socket.thread.EventThread.exec(EventThread.java:55) ~[OpenAudioMc.jar:?]
11.06 08:16:41 [Server] INFO at io.socket.engineio.client.Transport.open(Transport.java:77) ~[OpenAudioMc.jar:?]
11.06 08:16:41 [Server] INFO at io.socket.engineio.client.Socket.probe(Socket.java:472) ~[OpenAudioMc.jar:?]
11.06 08:16:41 [Server] INFO at io.socket.engineio.client.Socket.onOpen(Socket.java:485) ~[OpenAudioMc.jar:?]
11.06 08:16:41 [Server] INFO at io.socket.engineio.client.Socket.onHandshake(Socket.java:526) ~[OpenAudioMc.jar:?]
11.06 08:16:41 [Server] INFO at io.socket.engineio.client.Socket.onPacket(Socket.java:499) ~[OpenAudioMc.jar:?]
11.06 08:16:41 [Server] INFO at io.socket.engineio.client.Socket.access$1000(Socket.java:31) ~[OpenAudioMc.jar:?]
11.06 08:16:41 [Server] INFO at io.socket.engineio.client.Socket$5.call(Socket.java:313) ~[OpenAudioMc.jar:?]
11.06 08:16:41 [Server] INFO at io.socket.emitter.Emitter.emit(Emitter.java:117) ~[OpenAudioMc.jar:?]
```

**How to replicate the issue: Install Java 10**

**Comment by ApocalypsjeNL** [comment]
Looks like socket.io isn't supported on Java 10

**Comment by Mindgamesnl** [comment]
Should be fixed, pending for testing.

**Comment by Mindgamesnl** [comment]
Resolved.
